### ISSUE TITLE
All tests fail

### ISSUE THREAD

**Issue by olicairns** [statsbomb/statsbombpy#1]
All unit tests currently fail. Here is code to reproduce (MAC OS, Python 3.8.1, Conda 4.8.0)

    conda create -n statsbombpyenv python
    conda activate statsbombpyenv
    git clone https://github.com/statsbomb/statsbombpy.git
    cd statsbombpy
    pip install . 
    nose2 -v --pretty-assert
    #FAILED (failures=1, errors=4)

EDIT - maybe this is because I don't have credentials :). Strange because I can use the get_competitions() method from Readme with no issues.

**Comment by FranGoitia** [comment]
Yes. That's the issue.
