### ISSUE TITLE
Can we add Player Match Stats and summary of Player stats in a reason into the lib? 

### ISSUE THREAD

**Issue by SimonChicago** [statsbomb/statsbombpy#15]
### Contact Details

simonucla2012@gmail.com

### Version

1.0.1

### What platform are you seeing the problem on?

Windows

### What Python version are you running, are you using a virtual environment? Give us as much info as you can.

Python 3.7

### What happened?

Can we add more functions to get access to more tables in the Python API? 
Player Match Stats (https://data.statsbomb.com/api/v1/matches/?/player-stats)
Player Season Stats (https://data.statsbomb.com/api/v1/competitions/?/seasons/?/player-stats)
Team Season Stats (https://data.statsbomb.com/api/v1/competitions/?/seasons/?/team-stats)

**Comment by scottyj779** [comment]
Added functionality for the IQ APIs to `statsbombpy` version `1.2.0`.
