### ISSUE TITLE
Issue report

### ISSUE THREAD

**Issue by BabySharktududu** [statsbomb/statsbombpy#30]
### Contact Details

ben korman12@gmail.com

### Version

1.0.1

### What platform are you seeing the problem on?

Windows

### What Python version are you running, are you using a virtual environment? Give us as much info as you can.

Python 3.9.7

### What happened?

When observing locations (X,Y) of events regarding team X, how can you tell which direction they attack to?

**Comment by anenglishgoat** [comment]
Coordinates for all events and freeze frames assume that the acting player's team is attacking to the right (i.e. towards x = 120).

The data spec is available [here](https://github.com/statsbomb/statsbombpy/tree/master/doc).

**Comment by BabySharktududu** [comment]
The availability 🙌🏼
Thank you!!!
