### ISSUE TITLE
No open 360 data / include_360_metrics keyword not supported

### ISSUE THREAD

**Issue by wwwidonja** [statsbomb/statsbombpy#34]
### Contact Details

wwwidonja@gmail.com

### Version

1.0.1

### What platform are you seeing the problem on?

Windows

### What Python version are you running, are you using a virtual environment? Give us as much info as you can.

Anaconda environment running Python 3.7

### What happened?

After the latest commit to master, querying open 360 data with `sb.frames(match_id)` yields the following exception:

> Exception: There is currently no open 360 data, please provide credentials.

The commit message states that 360 data could be accessed directly from events by using `include_360_metrics=True`. However, adding this (to a match with open data available), the following `TypeError` is raised:

> TypeError: events() got an unexpected keyword argument 'include_360_metrics'

### Code to reproduce issue

```shell
frames = sb.frames(3795220)

evs = sb.events(3795220, split=True, flatten_attrs=False, include_360_metrics=True)
```

**Comment by WillTGM** [comment]
Hi,

Thanks for getting in touch. 

Can you check what version you're using? The latest version is `1.6.0` but according to the above you say you're on `1.0.1`? I can't reproduce the errors with the latest version.

Regarding retrieving the data and new metrics, I think we need to update the open data with the metrics included. We'll need to get back to you after the weekend sorry.

You should still be able to retrieve the raw frames though.

Thanks,
Will

**Comment by WillTGM** [comment]
We checked and we're not actually including the new metrics in the open data. We've made a [small update](https://pypi.org/project/statsbombpy/1.6.1/) (`1.6.1`) to reflect this and raise an exception if a user attempts to retrieve the 360 metrics from the open data.
