### ISSUE TITLE
Access with credentials

### ISSUE THREAD

**Issue by mcefis** [statsbomb/statsbombpy#36]
Good morning,

I have a problem: I'm trying to access with credentials at statsbomb data with your function, by using the "creds" argument, but it does not work: in particular, in order to do it, I'm using my Client ID and my Client Secret code: is it right? 

For instance, trying the following function the dataframe returned is empty.
**leagues=sb.competitions(creds={"user": my_code_user, "passwd": my_pw})**

Can you suggest me a possible solution? 

Many thanks, best regards

Mattia

**Comment by scotty779** [comment]
Hey Mattia,

Would you be able to email support@statsbomb.com then we can solve your issue through support? 

Thanks
