### ISSUE TITLE
'DataFrame' object has no attribute 'competition'

### ISSUE THREAD

**Issue by hadisotudeh** [statsbomb/statsbombpy#46]
When I want to iterate over all competitions to extract the matches, I get the following error, which seems to be an internal sb library issue, right?

![image](https://user-images.githubusercontent.com/2101643/227924955-6e50ee3f-a1dd-4747-858a-11b9dc38a3d5.png)

**Comment by scotty779** [comment]
Hey, what version of statsbombpy are you using? I'm struggling to replicate the error - are you accessing the open data competitions only?

**Comment by hadisotudeh** [comment]
Yes, below you can see the version. Only open data competitions. 

![image](https://user-images.githubusercontent.com/2101643/229484492-ce237680-c29c-421e-8969-e8ef0feec7d3.png)

**Comment by scotty779** [comment]
Ok it looks like this competition season is breaking it:
```
    competition_id  season_id country_name  competition_name season_name
              16         76       Europe  Champions League   1999/2000
```
I'll get that fixed but in the meantime, you can drop the above comp/season from the loop to fix it whilst we sort out the data. Also I recommend upgrading to the latest version of sbpy as it's quicker.

**Comment by jf632** [comment]
Hi, I am also getting the error with the 2015/16 Ligue 1 season: 
![image](https://github.com/statsbomb/statsbombpy/assets/92438846/b40939a2-5ffd-4068-a25d-be64a6dd0749)

**Comment by scotty779** [comment]
This has now been fixed, sorry it took so long!
