### ISSUE TITLE
No docummentation for 'visible area' in sb.frames

### ISSUE THREAD

**Issue by wwwidonja** [statsbomb/statsbombpy#51]
### Contact Details

wwwidonja@gmail.com

### Version

1.0.1

### What platform are you seeing the problem on?

Windows

### What Python version are you running, are you using a virtual environment? Give us as much info as you can.

3.8.

### What happened?

No docummentation is available for the 'visible area' in sb.frames(). What do the 10 fields correspond to?

**Comment by anenglishgoat** [comment]
They are the vertices of the visible area polygon in the format [x1, y1, x2, y2,...].

The visible area is the part of the pitch visible in the broadcast footage at the time the 360 frame was collected.

The docs for all of the open data are [here](https://github.com/statsbomb/open-data/tree/master/doc).
