### ISSUE TITLE
Trouble fetching frames for matches from open data competition 11, season 90

### ISSUE THREAD

**Issue by wwwidonja** [statsbomb/statsbombpy#56]
### Contact Details

wwwidonja@gmail.com

### Version

1.0.1

### What platform are you seeing the problem on?

Windows

### What Python version are you running, are you using a virtual environment? Give us as much info as you can.

I'm using a virtual environment Anaconda virtual environment, based on python 3.8.

### What happened?

Hi,

This is a duplicate from `open-data`, but I feel like it might have a place here instead.

For matches in the open data season of Barcelona matches `sb.matches(11, 90)`, I'm getting an error when trying to retrieve the 360 frames, even though they are said to be available in the matches dataframe. Other open data competitions, like the 2022 World Cup and the 2020 Euros, work fine.

Is this a known issue?

### Relevant log output
Example below for match id `3773565`:
```shell
from statsbombpy import sb


mid = 3773565
sb.frames(mid)

>raise HTTPError(http_error_msg, response=self)
>requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/statsbomb/open-data/master/data/three-sixty/3773565.json
````

### Code to reproduce issue

```shell
from statsbombpy import sb
mid = 3773565
sb.frames(mid)

```

### Attempted solutions

reinstalled statsbombpy and requests library.

**Comment by scotty779** [comment]
Hey, this is because we haven't made the 360 data available for that competition sorry.
