### ISSUE TITLE
No module named requests_cache

### ISSUE THREAD

**Issue by jackswales** [statsbomb/statsbombpy#62]
### Contact Details

swales.jack1@gmail.com

### Version

1.0.1

### What platform are you seeing the problem on?

Windows

### What Python version are you running, are you using a virtual environment? Give us as much info as you can.

3.12

### What happened?

When running from statsbombpy import sb, it returns:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 1
----> 1 from statsbombpy import sb

File ~\anaconda3\Lib\statsbombpy\sb.py:7
      3 from typing import Union
      5 import pandas as pd
----> 7 from statsbombpy import api_client, public
      8 from statsbombpy.config import DEFAULT_CREDS, MAX_CONCURRENCY
      9 from statsbombpy.helpers import (filter_and_group_events,
     10                                  merge_events_and_frames, reduce_events)

File ~\anaconda3\Lib\statsbombpy\api_client.py:5
      2 from tempfile import mkdtemp
      4 import requests as req
----> 5 from requests_cache import install_cache
      7 import statsbombpy.entities as ents
      8 from statsbombpy.config import CACHED_CALLS_SECS, HOSTNAME, VERSIONS

ModuleNotFoundError: No module named 'requests_cache'

I have followed instructions to install requests and requests-cache separately but had no luck

**Comment by scotty779** [comment]
I think wherever you're installing requests and requests-cache the python version you're using with statsbombpy isn't picking up on those installations. This might help with troubleshooting https://blog.finxter.com/fixed-modulenotfounderror-no-module-named-requests-cache/
